### TEST1. 주소에 따른 좌표 획득
### 투썸플레이스 파이낸셜뉴스빌딩점
### 서울 서초구 강남대로 315 파이낸셜뉴스빌딩
GET localhost:8080/api/v1/search?query=서울 서초구 강남대로 315 파이낸셜뉴스빌딩


### TEST2. 주소에 따른 좌표 획득
### 스타벅스 서초우성사거리점
### 서울 서초구 강남대로 343
GET localhost:8080/api/v1/search?query=서울 서초구 강남대로 343
